### ISSUE TITLE
Version as according to OpenVPN versions

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-easy-rsa#4]
We shouldn't be having a `HEAD`-only formula but should add versions as according to OpenVPN versions. Perhaps we can directly link the version to the OpenVPN Brew Formula?

**Comment by jjr840430** [comment]
@ronaldtse The `easy-rsa` also has its own version. To prevent conflicts by changes of the versions for `easy-rsa`,  I will modify the formula to specify the specific `branch` name.

**Comment by jjr840430** [comment]
@ronaldtse it seems to be fixed. Please check.
