### ISSUE TITLE
Replace `prog_vars=` and `set_var EASYRSA`

### ISSUE THREAD

**Issue by erikbor** [riboseinc/homebrew-easy-rsa#9]
Hi @jjr840430,

Instead of displaying a message after installation or setting an environment variable we can patch `easyrsa` to make use of the `PATH` of `easyrsa`:

```
$ diff -u /usr/local/bin/easyrsa ~/tmp/easyrsa-patched 
--- /usr/local/bin/easyrsa	2017-08-22 20:51:05.000000000 +0800
+++ /Users/test/tmp/easyrsa-patched	2018-01-18 10:59:59.000000000 +0800
@@ -1014,7 +1014,7 @@
 	local vars=
 
 	# set up program path
-	local prog_vars="${0%/*}/vars"
+	local prog_vars="$(dirname $(realpath ${0}))/vars"
 	# set up PKI path
 	local pki_vars="${EASYRSA_PKI:-$PWD/pki}/vars"
 
@@ -1041,7 +1041,7 @@
 	fi
 	
 	# Set defaults, preferring existing env-vars if present
-	set_var EASYRSA		"${0%/*}"
+	set_var EASYRSA		"$(dirname $(realpath ${0}))"
 	set_var EASYRSA_OPENSSL	openssl
 	set_var EASYRSA_PKI	"$PWD/pki"
 	set_var EASYRSA_DN	cn_only
```

Can you implement this patching in the formulae?

Thanks!!!

**Comment by ronaldtse** [comment]
@jjr840430 fully agree with @erikbor on this, this way once the formula is installed it would work immediately without any further instruction. Thanks!

This issue will fix #8 and #7 properly.

**Comment by thom-nic** [comment]
Very cool.  Can this facilitate managing multiple CAs?  e.g. let's say I have two different environments, each with their own independent PKI and CA.

I assumed one benefit for explicitly setting the `$EASYRSA` was you could have two different files pointing to different root dirs.  If `$EASYRSA` *is* set will that take priority?

**Comment by ronaldtse** [comment]
@thom-nic yes indeed! The `$EASYRSA` path (and others, like `EASYRSA_PKI`) will indeed take precedence over whatever is detected. The fix described here is just used to detect the "real" path of easyrsa and does not override anything else.

**Comment by jjr840430** [comment]
@erikbor `realpath` doesn't work on MacOS.

**Comment by erikbor** [comment]
@jjr840430 you are totally right :( I have `coreutils` installed on the dev macOS box I made that patch on.

Any suggestions for a work around? `$(cd $PWD; pwd)` or something like that?

**Comment by jjr840430** [comment]
I will try to find the solution, Thanks.

**Comment by erikbor** [comment]
A possible solution would be to make `easy-rsa` depend on `coreutils` but that might be a bit of an overkill. What do you think?

**Comment by jjr840430** [comment]
I think we may set environment variables based on the consistent path.

**Comment by erikbor** [comment]
`coreutils` from Homebrew fortunately has all the executables prepended with a `g`, e.g.: `/usr/local/Cellar/coreutils/8.29/bin/gecho` or `/usr/local/Cellar/coreutils/8.29/bin/gdirname` so there is no name collision with the executables on macOS.

Can you make `coreutils` a dependency of the formulae please? I suppose that's the fastest way of fixing this issue.

I do have some code lying somewhere to emulate `realpath` in Bash but it's a bit messy and I can't find it atm.

**Comment by jjr840430** [comment]
ok, I will try to solve it by adding `coreutils`. Thanks.

**Comment by jjr840430** [comment]
After modified the environment variables, I'm getting the following error:
```
devs-Mac-2:bin dev$ ./easyrsa init-pki
140736037028744:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 3

Easy-RSA error:

Missing or invalid OpenSSL
Expected to find openssl command at: openssl
```

**Comment by erikbor** [comment]
@jjr840430 
I can't replicate that, what is the value of the `PATH` environment variable?
The error message shows `libressl` so that's the openssl from the system and not the one from Homebrew.

**Comment by jjr840430** [comment]
@erikbor You are right, Currently `openssl` from `Homebrew` wasn't installed in `/usr/local/bin`

**Comment by jjr840430** [comment]
@erikbor I fixed `vars.example` and `easyrsa` shell script to use `easyrsa` without setting additional environment variables.
Please check #10
